apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  logLevel : 'debug'
  replicas: 2
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example